# coding: utf-8

"""
    VIER Cognitive Voice Dialog API

    CVG dialog history  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@vier.ai
    Generated by: https://openapi-generator.tech
"""

import unittest

import cvg_sdk
from cvg_sdk.model.custom_sip_headers import CustomSipHeaders
from cvg_sdk import configuration


class TestCustomSipHeaders(unittest.TestCase):
    """CustomSipHeaders unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
