
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-12T16:38:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f64738f205655f60670d1853ccdf6fa50a5f9bc9",
 "version": "0.28.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
