# Generated by Django 3.2.15 on 2022-10-12 04:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('cpu_usage', models.FloatField(verbose_name='CPU usage')),
                ('source_ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'System status',
                'verbose_name_plural': 'System statuses',
                'db_table': 'system_state',
            },
        ),
    ]
