
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-13T09:06:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c8c899155ca3609df8934688cc7071ab53f81a4",
 "version": "v0.8.0.rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
