
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-13T10:21:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9daa773677c51997acefc2d4348a0652b06a47f5",
 "version": "2.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
