
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-12T12:49:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7300efd69f9a5fde8a8cfb383baec49b34847337",
 "version": "0.4.158"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
