VERSION_YEAR = 2022
VERSION_MONTH = int('10')
VERSION_DAY = int('14')
VERSION_HOUR = int('03')
VERSION_MINUTE = int('11')
MAJOR_VERSION = 1
MINOR_VERSION = 6
PATCH_VERSION = 202210140311
version_date = '2022/10/14 03:11'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
