{
 "title": "Pod Health",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Pod Status",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} * 4) by(pod) + on(pod) sum(kube_pod_status_phase{phase=\"Succeeded\"} * 3) by(pod) + on(pod) sum(kube_pod_status_phase{phase=\"Pending\"}*2) by(pod) + on(pod) sum(kube_pod_status_phase{phase=\"Unknown\"} * 1) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", image!=\"\"}) by (pod) / on(pod) group_left sum(kube_pod_container_resource_limits_memory_bytes) by(pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\", container!=\"POD\"}[1m])) by(pod) / on() group_left sum(kube_pod_container_resource_limits_cpu_cores) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployment Status",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable * -10) by(deployment) + on(deployment) sum(kube_deployment_status_replicas_available * 4) by(deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Running/Successful" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Running\"} + ignoring(phase) kube_pod_status_phase{phase=\"Succeeded\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{}) by(deployment) / sum(kube_deployment_status_replicas{}) by(deployment)"
    }
   ]
  }
 ]
}