"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import aptible_client
from aptible_client.api.environments_api import EnvironmentsApi  # noqa: E501


class TestEnvironmentsApi(unittest.TestCase):
    """EnvironmentsApi unit test stubs"""

    def setUp(self):
        self.api = EnvironmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_environment_create(self):
        """Test case for environment_create

        Environment Create  # noqa: E501
        """
        pass

    def test_environment_delete(self):
        """Test case for environment_delete

        Environment Delete  # noqa: E501
        """
        pass

    def test_environment_get(self):
        """Test case for environment_get

        Environment Get  # noqa: E501
        """
        pass

    def test_environment_get_allowed_asset_bundles(self):
        """Test case for environment_get_allowed_asset_bundles

        Environment Get Allowed Asset Bundles  # noqa: E501
        """
        pass

    def test_environment_get_assets(self):
        """Test case for environment_get_assets

        Environment Get Assets  # noqa: E501
        """
        pass

    def test_environment_get_connections(self):
        """Test case for environment_get_connections

        Environment Get Connections  # noqa: E501
        """
        pass

    def test_environment_update(self):
        """Test case for environment_update

        Environment Update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
