"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aptible_client
from aptible_client.model.health_check_from_worker import HealthCheckFromWorker


class TestHealthCheckFromWorker(unittest.TestCase):
    """HealthCheckFromWorker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthCheckFromWorker(self):
        """Test HealthCheckFromWorker"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HealthCheckFromWorker()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
