"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aptible_client
from aptible_client.model.asset_parameters_output import AssetParametersOutput
from aptible_client.model.asset_status import AssetStatus
from aptible_client.model.asset_terraform_output import AssetTerraformOutput
from aptible_client.model.connection_output import ConnectionOutput
from aptible_client.model.environment_output import EnvironmentOutput
globals()['AssetParametersOutput'] = AssetParametersOutput
globals()['AssetStatus'] = AssetStatus
globals()['AssetTerraformOutput'] = AssetTerraformOutput
globals()['ConnectionOutput'] = ConnectionOutput
globals()['EnvironmentOutput'] = EnvironmentOutput
from aptible_client.model.asset_output import AssetOutput


class TestAssetOutput(unittest.TestCase):
    """AssetOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetOutput(self):
        """Test AssetOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
