# coding: utf-8


"""
IGNORE:
    Nutanix Lcm Versioned APIs

    Manage Infrastructure, Software and Firmware Upgrades.  # noqa: E501

    OpenAPI spec version: 4.0.1-alpha-1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
IGNORE
"""
import pprint
import json
import ast
import re  # noqa: F401

import six
from ntnx_lcm_py_client.Ntnx.lcm.v4.common.LcmEntityType import LcmEntityType  # noqa: F401,E501
from ntnx_lcm_py_client.Ntnx.lcm.v4.resources.LcmImageFile import LcmImageFile  # noqa: F401,E501

"""
IGNORE:
NOTE: This class is auto generated by the swagger code generator program.

Do not edit the class manually.
IGNORE
"""


class LcmImage(object):
    """LcmImage - a model defined in Swagger"""
    """
    IGNORE:
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    IGNORE
    """ # noqa: E501
    swagger_types = {
        'entity_class': 'str',
        'entity_type': 'lcm.v4.common.LcmEntityType',
        'entity_model': 'str',
        'hardware_family': 'str',
        'version': 'str',
        'files': 'list[lcm.v4.resources.LcmImageFile]',
        '_reserved': 'dict(str, object)',
        '_object_type': 'str',
        '_unknown_fields': 'dict(str, object)',
    }

    attribute_map = {
        'entity_class': 'entityClass',
        'entity_type': 'entityType',
        'entity_model': 'entityModel',
        'hardware_family': 'hardwareFamily',
        'version': 'version',
        'files': 'files',
        '_reserved': '$reserved',
        '_object_type': '$objectType',
        '_unknown_fields': '$unknownFields',
    }



    def __init__(self, entity_class=None, entity_type=None, entity_model=None, hardware_family=None, version=None, files=None, *args, **kwargs):  # noqa: E501
        """LcmImage - a model defined in Swagger
            \nLCM image (List of LCM image files)
        """
        self.__entity_class = None
        self.__entity_type = None
        self.__entity_model = None
        self.__hardware_family = None
        self.__version = None
        self.__files = None
        self.discriminator = None
        if entity_class is not None:
            self.__entity_class = entity_class
        if entity_type is not None:
            self.__entity_type = entity_type
        if entity_model is not None:
            self.__entity_model = entity_model
        if hardware_family is not None:
            self.__hardware_family = hardware_family
        if version is not None:
            self.__version = version
        if files is not None:
            self.__files = files
        # populate hidden vars if not empty
        self._populate_hidden_vars(kwargs)

    def _initialize_object_type(self):
        return 'lcm.v4.resources.LcmImage'

    def _initialize_fq_object_type(self):
        return 'lcm.v4.r0.a1.resources.LcmImage'

    def _populate_hidden_vars(self, kwargs):
        if "_reserved" in kwargs and kwargs["_reserved"] is not None:
            self.__dollar_reserved = kwargs["_reserved"]
        elif "_reserved" in self.attribute_map and self.attribute_map["_reserved"] in kwargs and kwargs[self.attribute_map["_reserved"]] is not None:
            self.__dollar_reserved = kwargs[self.attribute_map["_reserved"]]
        else :
            self.__dollar_reserved = {"$fqObjectType": self._initialize_fq_object_type()}
        if "_unknown_fields" in kwargs and kwargs["_unknown_fields"] is not None:
            self.__dollar_unknown_fields = kwargs["_unknown_fields"]
        elif "_unknown_fields" in self.attribute_map and self.attribute_map["_unknown_fields"] in kwargs and kwargs[self.attribute_map["_unknown_fields"]] is not None:
            self.__dollar_unknown_fields = kwargs[self.attribute_map["_unknown_fields"]]
        else :
            self.__dollar_unknown_fields = {}
        if "_object_type" in kwargs and kwargs["_object_type"] is not None:
            self.__dollar_object_type = kwargs["_object_type"]
        elif "_object_type" in self.attribute_map and self.attribute_map["_object_type"] in kwargs and kwargs[self.attribute_map["_object_type"]] is not None:
            self.__dollar_object_type = kwargs[self.attribute_map["_object_type"]]
        else:
            self.__dollar_object_type = self._initialize_object_type()

    def get_object_type(self):
        return self.__dollar_object_type

    def get_reserved(self):
        return self.__dollar_reserved

    def get_unknown_fields(self):
        return self.__dollar_unknown_fields

    @property
    def entity_class(self):
        """`{ str }`
            \nLCM entity class
        """ # noqa: E501
        return self.__entity_class

    @entity_class.setter
    def entity_class(self, entity_class):

        self.__entity_class = entity_class

    @property
    def entity_type(self):
        """`{ lcm.v4.common.LcmEntityType }`
            
        """ # noqa: E501
        return self.__entity_type

    @entity_type.setter
    def entity_type(self, entity_type):

        self.__entity_type = entity_type

    @property
    def entity_model(self):
        """`{ str }`
            \nLCM entity model
        """ # noqa: E501
        return self.__entity_model

    @entity_model.setter
    def entity_model(self, entity_model):

        self.__entity_model = entity_model

    @property
    def hardware_family(self):
        """`{ str }`
            \nA hardware family for a LCM entity
        """ # noqa: E501
        return self.__hardware_family

    @hardware_family.setter
    def hardware_family(self, hardware_family):

        self.__hardware_family = hardware_family

    @property
    def version(self):
        """`{ str }`
            \nCurrent version of an LCM entity
        """ # noqa: E501
        return self.__version

    @version.setter
    def version(self, version):

        self.__version = version

    @property
    def files(self):
        """`{ list[lcm.v4.resources.LcmImageFile] }`
            \nList of files in the image
        """ # noqa: E501
        return self.__files

    @files.setter
    def files(self, files):

        self.__files = files

    @property
    def _reserved(self):
        """`{ dict(str, object) }`
            
        """ # noqa: E501
        return self.__dollar_reserved

    @property
    def _object_type(self):
        """`{ str }`
            
        """ # noqa: E501
        return self.__dollar_object_type

    @property
    def _unknown_fields(self):
        """`{ dict(str, object) }`
            
        """ # noqa: E501
        return self.__dollar_unknown_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LcmImage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LcmImage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

