
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-12T17:07:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbb54bdd5fc8554629a55442024ed7b665e9de0e",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
