
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-14T12:24:15+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6a90cdf2b20bc1253998eaaca4a82c3d091e99a",
 "version": "0.0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
