from typing import TypeVar

from .EventContainer import EventContainer
from .BaseEvent import BaseEvent
from .MixinSignEditScreen import MixinSignEditScreen
from .MixinHungerManager import MixinHungerManager
from .MixinRecipeBookWidget import MixinRecipeBookWidget
from .MixinFontManager import MixinFontManager
from .MixinChunkSelection import MixinChunkSelection
from .IMixinEntity import IMixinEntity
from .MixinLivingEntity import MixinLivingEntity
from .MixinMinecraftClient import MixinMinecraftClient
from .MixinPackedIntegerArray import MixinPackedIntegerArray
from .MixinClientPlayNetworkHandler import MixinClientPlayNetworkHandler
from .MixinClientPlayerEntity import MixinClientPlayerEntity
from .MixinMerchantEntity import MixinMerchantEntity
from .MixinDisconnectedScreen import MixinDisconnectedScreen
from .MixinSplashOverlay import MixinSplashOverlay
from .MixinTrueTypeFont import MixinTrueTypeFont
from .MixinClientPlayerInteractionManager import MixinClientPlayerInteractionManager
from .MixinHorseScreen import MixinHorseScreen
from .MixinCreativeInventoryScreen import MixinCreativeInventoryScreen
from .MixinChatHud import MixinChatHud
from .MixinPalettedContainer import MixinPalettedContainer
from .MixinLoomScreen import MixinLoomScreen
from .MixinSimpleOption import MixinSimpleOption
from .MixinItemCooldownManager import MixinItemCooldownManager
from .MixinResourcePackManager import MixinResourcePackManager
from .MixinHandledScreen import MixinHandledScreen
from .MixinClientWorld import MixinClientWorld
from .MixinSoundSystem import MixinSoundSystem
from .MixinTranslationStorage import MixinTranslationStorage
from .MixinBeaconScreen import MixinBeaconScreen
from .MixinPlayerListHud import MixinPlayerListHud
from .MixinItemCooldownEntry import MixinItemCooldownEntry
from .MixinFontStorage import MixinFontStorage
from .MixinBossBarHud import MixinBossBarHud
from .MixinEntity import MixinEntity
from .MixinPlayerEntity import MixinPlayerEntity
from .MixinRecipeBookResults import MixinRecipeBookResults
from .MixinMerchantScreen import MixinMerchantScreen
from .MixinStyleSerializer import MixinStyleSerializer
from .MixinStatHandler import MixinStatHandler
from .MixinScreen import MixinScreen
from .MixinPalettedContainerData import MixinPalettedContainerData

File = TypeVar["java.io.File"]

