
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-10T18:08:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c46ae31bf2dc9d76589a5b8142b8130a157b3329",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
