
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-11T13:25:04+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "b954548e24bf31d911def9acc94c7ebbbfb1028d",
 "version": "0.2.58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
