
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-14T14:40:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "68dabb10735e3e4670113b3f57cbe697188db796",
 "version": "2778"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
