
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-14T11:45:35-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "af8317ee2c049977c6e20e6cec683a29a4232589",
 "version": "v0.1.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
