
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-11T16:59:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab23885d1f8e9af1fa4f03608558d655136975ed",
 "version": "0.2.31.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
