"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aptible_client
from aptible_client.model.operation_type import OperationType


class TestOperationType(unittest.TestCase):
    """OperationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationType(self):
        """Test OperationType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OperationType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
