"""
    Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aptible_client
from aptible_client.model.action_output import ActionOutput


class TestActionOutput(unittest.TestCase):
    """ActionOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionOutput(self):
        """Test ActionOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActionOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
