from typing import TypeVar

from .EventContainer import EventContainer
from .BaseEvent import BaseEvent
from .EventEXPChange import EventEXPChange
from .EventCustom import EventCustom
from .EventRecvMessage import EventRecvMessage
from .EventWrappedScript import EventWrappedScript
from .EventAirChange import EventAirChange
from .CodeCompileEvent import CodeCompileEvent
from .EventResourcePackLoaded import EventResourcePackLoaded
from .EventItemDamage import EventItemDamage
from .EventJoinedTick import EventJoinedTick
from .EventTitle import EventTitle
from .EventOpenContainer import EventOpenContainer
from .EventBossbar import EventBossbar
from .EventAttackBlock import EventAttackBlock
from .EventDamage import EventDamage
from .EventPlayerLeave import EventPlayerLeave
from .EventChunkLoad import EventChunkLoad
from .EventHungerChange import EventHungerChange
from .EventDropSlot import EventDropSlot
from .EventRiding import EventRiding
from .EventJoinServer import EventJoinServer
from .EventEntityUnload import EventEntityUnload
from .EventEntityDamaged import EventEntityDamaged
from .EventFallFlying import EventFallFlying
from .EventDisconnect import EventDisconnect
from .EventInteractBlock import EventInteractBlock
from .EventHeal import EventHeal
from .EventInteractEntity import EventInteractEntity
from .EventBlockUpdate import EventBlockUpdate
from .EventEntityHealed import EventEntityHealed
from .EventClickSlot import EventClickSlot
from .EventDimensionChange import EventDimensionChange
from .EventItemPickup import EventItemPickup
from .EventOpenScreen import EventOpenScreen
from .EventDeath import EventDeath
from .EventSignEdit import EventSignEdit
from .EventAttackEntity import EventAttackEntity
from .EventSendMessage import EventSendMessage
from .CommandContextHelper import CommandContextHelper
from .EventTick import EventTick
from .EventJoinedKey import EventJoinedKey
from .EventSound import EventSound
from .EventKey import EventKey
from .EventProfileLoad import EventProfileLoad
from .EventService import EventService
from .EventEntityLoad import EventEntityLoad
from .EventChunkUnload import EventChunkUnload
from .EventArmorChange import EventArmorChange
from .EventPlayerJoin import EventPlayerJoin
from .EventHeldItemChange import EventHeldItemChange

File = TypeVar["java.io.File"]

