# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import cvg_sdk
from cvg_sdk.paths.health_reseller_token_project_project_token import get  # noqa: E501
from cvg_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestHealthResellerTokenProjectProjectToken(ApiTestMixin, unittest.TestCase):
    """
    HealthResellerTokenProjectProjectToken unit test stubs
        Get the health status of a project based on calls within a time range (by default the last 10 minutes). NOTE: this API is still experimental and subject to change.  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
