
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-14T11:39:23-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1c16d76d9b4ffd1ba265d4e0d0dd646472a8eb4",
 "version": "0.1.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
