
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-12T14:25:10+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "48a7fccab0a29b093f38757b13d738f6b72d01d1",
 "version": "3.17.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
