from enum import Enum


class WebsocketMessageType(Enum):
    state = "state"
    cmd = "cmd"
    route = "route"


class CarCommand(Enum):
    alarm_start = "Подать сигнал"
    alarm_stop = "Отключить сигнал"
    service_start = "Активировать автосервис"
    service_stop = "Автосервис отключить"
    pre_heater_start = "Включить подогреватель"
    pre_heater_stop = "Отключить подогреватель"
    pre_heater_control = "Включение предпускового подогревателя"
    arm = "Поставить на охрану"
    disarm = "Снять с охраны"
    clear_immo = "Разрешить поездку"
    door_open = "Открыть двери"
    door_close = "Закрыть двери"
    trunk_open = "Открыть багажник"
    trunk_close = "Закрыть багажник"
    prog_1 = "Команда 1 допканал"
    prog_2 = "Команда 2 допканал"
    prog_3 = "Команда 3 допканал"
    prog_4 = "Команда 4 допканал"
    prog_5 = "Команда 5 допканал"
    prog_6 = "Команда 6 допканал"
    prog_7 = "Команда 7 допканал"
    prog_8 = "Команда 8 допканал"
    auto_hijack_start = "Включить защита от"
    auto_hijack_stop = "Отключить защита от"
    central_lock = "Центральный замок"
    get_info = "Обновить статус"
    update_firmware = "Обновление прошивки устройства"
    update_settings = "Обновление настроек устройства"
    update_balance = "Обновление баланса устройства"
    engine_start = "Завести двигатель"
    engine_stop = "Остановить двигатель"
    arm_quiet = "Тихое включение режима Охраны"
    disarm_quiet = "Тихое выключение режима Охраны"
    ign_support_on = "Включение поддержки зажигания"
    panic_stop = "Остановить Панику"
    pit_stop_start = "Включение режима ПИТ-Стоп"
    obd_data_get = "OBD диагностики устройства"
    obd_error_clear = "Очистка ошибок"
    get_settings = "Получение настроек из устройства"
