
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-14T14:52:20+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "395e09d910bca203fb471babbf05a0863865b17b",
 "version": "2.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
