class AppAttrName:
    availability_zone = "Availability Zone"
    image_id = "Image ID"
    instance_flavor = "Instance Flavor"
    add_floating_ip = "Add Floating IP"
    affinity_group_id = "Affinity Group ID"
    floating_ip_subnet_id = "Floating IP Subnet ID"
    auto_udev = "Auto udev"
    user_data = "User data"
    inbound_ports = "Inbound Ports"
    behavior_during_save = "Behavior during save"
    private_ip = "Private IP"
