# coding: utf-8


"""
IGNORE:
    Nutanix Lcm Versioned APIs

    Manage Infrastructure, Software and Firmware Upgrades.  # noqa: E501

    OpenAPI spec version: 4.0.1-alpha-1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
IGNORE
"""
import pprint
import json
import ast
import re  # noqa: F401

import six
from ntnx_lcm_py_client.Ntnx.lcm.v4.common.EntityUpdateSpec import EntityUpdateSpec  # noqa: F401,E501
from ntnx_lcm_py_client.Ntnx.lcm.v4.common.ManagementServer import ManagementServer  # noqa: F401,E501
from ntnx_lcm_py_client.Ntnx.lcm.v4.common.SystemAutoMgmtFlag import SystemAutoMgmtFlag  # noqa: F401,E501

"""
IGNORE:
NOTE: This class is auto generated by the swagger code generator program.

Do not edit the class manually.
IGNORE
"""


class PrecheckSpec(object):
    """PrecheckSpec - a model defined in Swagger"""
    """
    IGNORE:
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    IGNORE
    """ # noqa: E501
    swagger_types = {
        'management_server': 'lcm.v4.common.ManagementServer',
        'entity_update_specs': 'list[lcm.v4.common.EntityUpdateSpec]',
        'skipped_precheck_flags': 'list[lcm.v4.common.SystemAutoMgmtFlag]',
        '_reserved': 'dict(str, object)',
        '_object_type': 'str',
        '_unknown_fields': 'dict(str, object)',
    }

    attribute_map = {
        'management_server': 'managementServer',
        'entity_update_specs': 'entityUpdateSpecs',
        'skipped_precheck_flags': 'skippedPrecheckFlags',
        '_reserved': '$reserved',
        '_object_type': '$objectType',
        '_unknown_fields': '$unknownFields',
    }



    def __init__(self, management_server=None, entity_update_specs=None, skipped_precheck_flags=None, *args, **kwargs):  # noqa: E501
        """PrecheckSpec - a model defined in Swagger
            \nSpecification for running a Precheck operation
        """
        self.__management_server = None
        self.__entity_update_specs = None
        self.__skipped_precheck_flags = None
        self.discriminator = None
        if management_server is not None:
            self.__management_server = management_server
        if entity_update_specs is not None:
            self.__entity_update_specs = entity_update_specs
        if skipped_precheck_flags is not None:
            self.__skipped_precheck_flags = skipped_precheck_flags
        # populate hidden vars if not empty
        self._populate_hidden_vars(kwargs)

    def _initialize_object_type(self):
        return 'lcm.v4.common.PrecheckSpec'

    def _initialize_fq_object_type(self):
        return 'lcm.v4.r0.a1.common.PrecheckSpec'

    def _populate_hidden_vars(self, kwargs):
        if "_reserved" in kwargs and kwargs["_reserved"] is not None:
            self.__dollar_reserved = kwargs["_reserved"]
        elif "_reserved" in self.attribute_map and self.attribute_map["_reserved"] in kwargs and kwargs[self.attribute_map["_reserved"]] is not None:
            self.__dollar_reserved = kwargs[self.attribute_map["_reserved"]]
        else :
            self.__dollar_reserved = {"$fqObjectType": self._initialize_fq_object_type()}
        if "_unknown_fields" in kwargs and kwargs["_unknown_fields"] is not None:
            self.__dollar_unknown_fields = kwargs["_unknown_fields"]
        elif "_unknown_fields" in self.attribute_map and self.attribute_map["_unknown_fields"] in kwargs and kwargs[self.attribute_map["_unknown_fields"]] is not None:
            self.__dollar_unknown_fields = kwargs[self.attribute_map["_unknown_fields"]]
        else :
            self.__dollar_unknown_fields = {}
        if "_object_type" in kwargs and kwargs["_object_type"] is not None:
            self.__dollar_object_type = kwargs["_object_type"]
        elif "_object_type" in self.attribute_map and self.attribute_map["_object_type"] in kwargs and kwargs[self.attribute_map["_object_type"]] is not None:
            self.__dollar_object_type = kwargs[self.attribute_map["_object_type"]]
        else:
            self.__dollar_object_type = self._initialize_object_type()

    def get_object_type(self):
        return self.__dollar_object_type

    def get_reserved(self):
        return self.__dollar_reserved

    def get_unknown_fields(self):
        return self.__dollar_unknown_fields

    @property
    def management_server(self):
        """`{ lcm.v4.common.ManagementServer }`
            
        """ # noqa: E501
        return self.__management_server

    @management_server.setter
    def management_server(self, management_server):

        self.__management_server = management_server

    @property
    def entity_update_specs(self):
        """`{ list[lcm.v4.common.EntityUpdateSpec] }`
            
        """ # noqa: E501
        return self.__entity_update_specs

    @entity_update_specs.setter
    def entity_update_specs(self, entity_update_specs):

        self.__entity_update_specs = entity_update_specs

    @property
    def skipped_precheck_flags(self):
        """`{ list[lcm.v4.common.SystemAutoMgmtFlag] }`
            \nList of prechecks to skip. The allowed value is 'power_off_vm' that skips the pinned VM prechecks
        """ # noqa: E501
        return self.__skipped_precheck_flags

    @skipped_precheck_flags.setter
    def skipped_precheck_flags(self, skipped_precheck_flags):

        self.__skipped_precheck_flags = skipped_precheck_flags

    @property
    def _reserved(self):
        """`{ dict(str, object) }`
            
        """ # noqa: E501
        return self.__dollar_reserved

    @property
    def _object_type(self):
        """`{ str }`
            
        """ # noqa: E501
        return self.__dollar_object_type

    @property
    def _unknown_fields(self):
        """`{ dict(str, object) }`
            
        """ # noqa: E501
        return self.__dollar_unknown_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrecheckSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrecheckSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

