
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-12T10:03:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "89125571f90f3c806540e2aafe13ef419dab1d1e",
 "version": "2777"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
