class ProtocolVersionError(Exception): ...

class MessageError(Exception): ...

class InvocationError(ValueError): ...
        
class BatchShapeError(Exception): ...

class ParseAddressError(Exception): ...

