
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-14T18:06:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b96e6c6ab3c20c42748c30f9e7dc5f26b69cd3ee",
 "version": "0.9.76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
